// Core - State management
export {
  useStore,
  resetStore,
  useRepo,
  useEntity,
  useRelation,
  useRelations,
  useQuery,
  useSync,
  defineConfig,
  getConfig,
} from './core'

export type {
  Entity,
  EntitySchema,
  StoreState,
  Store,
  SyncConfig,
  NavigationConfig,
  MobileKitConfig,
  QueryOptions,
} from './core'

// Entity - Schema & Faker
export {
  entity,
  getEntityDefinition,
  getEntityRegistry,
  seed,
  fake,
  clearEntityRegistry,
  generateFakeValue,
  generateFakeData,
} from './entity'

export type {
  FieldType,
  FieldDefinition,
  FieldsDefinition,
  EntityDefinition,
  InferEntity,
  InferEntityFromFields,
} from './entity'

// Auth
export {
  // Store
  getAuthStore,
  resetAuth,
  resetAllAuth,
  getActiveNamespaces,
  getAllSessions,
  // Hooks
  useAuth,
  useUser,
  useIsAuthenticated,
  useCurrentUserId,
  useRequireAuth,
  // Components
  RequireAuth,
  RequireRole,
  AuthGuard,
  RoleGuard,
  AccessDenied,
  OTPAuth,
  // Registry
  defineUsers,
  defineRoles,
  getAppUsers,
  getAppRoles,
  getAllAppUsers,
  getAllAppRoles,
  getTestUser,
  getRole,
  getRegisteredAppIds,
  // Quick Switch
  quickSwitch,
  quickLogout,
} from './auth'

export type {
  AuthUser,
  AuthState,
  AuthActions,
  UseAuthOptions,
  UseAuthReturn,
  RequireAuthProps,
  RequireRoleProps,
  AccessDeniedProps,
  OTPAuthProps,
  OTPAuthStep,
  SessionInfo,
  TestUser,
  RoleDefinition,
  AppUsers,
  AppRoles,
} from './auth'

// UI Components
export {
  // Theme
  ThemeProvider,
  useTheme,
  usePlatform,
  platformSelect,
  // Typography
  Text,
  Title,
  Subtitle,
  Caption,
  Label,
  // Layout
  Screen,
  ScrollView,
  Section,
  Content,
  Header,
  BackButton,
  IconButton,
  Card,
  Divider,
  Spacer,
  // Interactive
  Button,
  TextButton,
  Input,
  Select,
  TextArea,
  Switch,
  Checkbox,
  Radio,
  RadioGroup,
  Slider,
  SearchBar,
  SearchableSelect,
  Autocomplete,
  CurrencyInput,
  PriceRange,
  AmountInput,
  formatCurrency,
  CURRENCIES,
  // Data display
  List,
  ListItem,
  MenuItem,
  Avatar,
  AvatarGroup,
  Badge,
  Chip,
  StatusBadge,
  OrderStatusBadge,
  UserStatusBadge,
  InfoRow,
  InfoGroup,
  StatCard,
  StatGrid,
  DashboardStats,
  QueryList,
  Tabs,
  TabBar,
  Accordion,
  AccordionGroup,
  AccordionItem,
  Carousel,
  // Menus
  DropdownMenu,
  HorizontalMenu,
  ContextMenu,
  // Overlays
  BottomSheet,
  ActionSheet,
  Modal,
  Alert,
  Confirm,
  Prompt,
  ToastProvider,
  useToast,
  ImageViewer,
  Gallery,
  // Pickers
  DatePicker,
  Calendar,
  TimePicker,
  DateTimePicker,
  // Feedback
  Spinner,
  LoadingOverlay,
  ProgressBar,
  CircularProgress,
  FAB,
  SpeedDial,
  ActionFooter,
  SubmitFooter,
  ErrorBoundary,
  // Onboarding
  Onboarding,
  // Locale
  setLocale,
  useLocale,
  isRTL,
  getLocale,
  LOCALES,
  // Utils
  cn,
} from './ui'

export type {
  Platform,
  ThemeColors,
  ThemeConfig,
  ThemeProviderProps,
  // Typography
  TextProps,
  // Layout
  ScreenProps,
  ScrollViewProps,
  SectionProps,
  ContentProps,
  HeaderProps,
  BackButtonProps,
  IconButtonProps,
  CardProps,
  DividerProps,
  SpacerProps,
  ButtonProps,
  TextButtonProps,
  InputProps,
  SelectProps,
  SelectOption,
  TextAreaProps,
  SwitchProps,
  CheckboxProps,
  RadioProps,
  RadioGroupProps,
  RadioGroupOption,
  SliderProps,
  SearchBarProps,
  SearchableSelectProps,
  SearchableSelectOption,
  AutocompleteProps,
  AutocompleteOption,
  CurrencyInputProps,
  PriceRangeProps,
  AmountInputProps,
  ListProps,
  ListItemProps,
  MenuItemProps,
  AvatarProps,
  AvatarGroupProps,
  BadgeProps,
  ChipProps,
  // New helpers
  StatusBadgeProps,
  StatusConfig,
  InfoRowProps,
  InfoGroupProps,
  StatCardProps,
  StatGridProps,
  DashboardStatsProps,
  QueryListProps,
  ActionFooterProps,
  FooterAction,
  SubmitFooterProps,
  ErrorBoundaryProps,
  // Tabs
  TabsProps,
  TabBarProps,
  Tab,
  TabBarItem,
  AccordionProps,
  AccordionGroupProps,
  AccordionItemProps,
  CarouselProps,
  CarouselItem,
  DropdownMenuProps,
  DropdownMenuItem,
  HorizontalMenuProps,
  HorizontalMenuItem,
  ContextMenuProps,
  BottomSheetProps,
  ActionSheetProps,
  ActionSheetOption,
  ModalProps,
  AlertProps,
  ConfirmProps,
  PromptProps,
  AlertButton,
  ToastProviderProps,
  ToastType,
  ToastData,
  ImageViewerProps,
  ImageViewerImage,
  GalleryProps,
  DatePickerProps,
  CalendarProps,
  TimePickerProps,
  DateTimePickerProps,
  SpinnerProps,
  LoadingOverlayProps,
  ProgressBarProps,
  CircularProgressProps,
  FABProps,
  SpeedDialProps,
  SpeedDialAction,
  LocaleCode,
  UILocale,
  OnboardingProps,
  OnboardingSlide,
} from './ui'

// Canvas - Multi-app layout
export {
  Canvas,
  DeviceFrame,
  useApp,
  defineApp,
  DEVICE_PRESETS,
} from './canvas'

export type {
  CanvasProps,
  DeviceFrameProps,
  DeviceType,
  DeviceConfig,
  AppDefinition,
  CanvasLayout,
  CanvasConfig,
  UseAppReturn,
} from './canvas'

// Events
export {
  eventBus,
  dispatch,
  subscribe,
  getEventHistory,
  clearEventHistory,
  defineEvents,
  createEvent,
  useEvent,
  useDispatch,
  useEventHistory,
  useLatestEvent,
} from './events'

export type {
  EventDefinition,
  EventsDefinition,
  EventRecord,
  EventHandler,
  TypedDispatcher,
} from './events'

// DevTools
export {
  DevTools,
  StateInspector,
  EventLog,
} from './devtools'

export type {
  DevToolsProps,
  DevToolsTab,
  StateInspectorProps,
  EventLogProps,
} from './devtools'

// Frames - Screen registry and browser
export {
  // Registry
  registerFrames,
  unregisterFrames,
  getAllApps,
  getAppFrames,
  getFrame,
  getFrameCount,
  searchFrames,
  setNavigationCallback,
  navigateToFrame,
  clearRegistry,
  defineFrames,
  createFrame,
  // Flow Registry
  registerFlow,
  unregisterFlow,
  getAllFlows,
  getAppFlows,
  getFlow,
  subscribeFlows,
  clearFlowRegistry,
  defineFlow,
  getFlowProgress,
  toggleStepComplete,
  toggleTaskComplete,
  resetFlowProgress,
  isStepComplete,
  isTaskComplete,
  // Hooks
  useFrameRegistry,
  useAppFrames,
  useFrame,
  // Components
  FrameBrowser,
} from './frames'

export type {
  Frame,
  AppFrames,
  FrameRegistryState,
  FrameNavigationRequest,
  FrameDefinitionInput,
  FrameInput,
  Flow,
  FlowStep,
  FlowDefinitionInput,
  FlowProgress,
  FrameBrowserProps,
} from './frames'

// Utils - Date formatting
export {
  dayjs,
  timeAgo,
  timeFromNow,
  smartDate,
  smartDateShort,
  formatDate,
  isDateToday,
  isDateYesterday,
  isPast,
  isFuture,
  dateDiff,
  addTime,
  subtractTime,
  startOf,
  endOf,
  formatDuration,
  formatDurationHuman,
  parseDate,
  isValidDate,
  getMonthNames,
  getDayNames,
} from './utils'

// Forms
export {
  // Core hook
  useForm,
  // Validators
  validators,
  required,
  minLength,
  maxLength,
  email,
  phone,
  range,
  min,
  max,
  pattern,
  url,
  match,
  custom,
  compose,
  optional,
  // Form components
  Form,
  FormField,
  FormRow,
  FormSection,
  FormActions,
  useFormContext,
  // EntityForm
  EntityForm,
  // FormWizard
  FormWizard,
  useWizard,
  // Specialized inputs
  PhoneInput,
  OTPInput,
  PinInput,
} from './forms'

export type {
  Validator,
  FieldState,
  FormState,
  UseFormOptions,
  FieldProps,
  UseFormReturn,
  FormProps,
  FormFieldProps,
  FormRowProps,
  FormSectionProps,
  FormActionsProps,
  EntityFormProps,
  FormWizardProps,
  FormWizardStepProps,
  PhoneInputProps,
  OTPInputProps,
  PinInputProps,
} from './forms'

// Navigation
export {
  Navigator,
  useNavigate,
  useRoute,
  TabNavigator,
  useTab,
  // Screen Registry API
  getScreens,
  getScreenNames,
  hasScreen,
  subscribeToScreenRegistry,
  parseHash,
  buildHash,
} from './navigation'

export type {
  RouteParams,
  ScreenProps as NavScreenProps,
  NavigationActions,
  Route,
  NavigationState,
  ScreenDefinition,
  ScreenOptions,
  NavigatorProps,
  TabDefinition,
  TabNavigatorProps,
  ScreenRegistryEntry,
} from './navigation'
